server:
  port: 8081
spring:
  servlet:
    multipart:
      max-file-size: 1000000000000
      max-request-size: 1000000000000
  datasource:
    url: jdbc:mysql://47.93.122.204:3306/ydyp?useUnicode=true&characterEncoding=utf-8
    username: root
    password: asdfgh123456